### ISSUE TITLE
Where are "./data_tools/mean_var_calculator.py" and "./data_tools/mean_var_calculator_jpg.py"?

### ISSUE THREAD

**Issue by Another-0** [jonggyujang0123/M2SODAI#1]

**Comment by jonggyujang0123** [comment]
First and foremost, I would like to express my sincere gratitude for your interest in our work. 
Regarding the recent communication, I must extend my apologies for the confusion caused by the errors in the file upload.

I am currently aiming to finish all necessary tasks by the end of February or early March at the latest.

Thank you again for your kind interest. 

I will close this comment, if the process is finished.

**Comment by jonggyujang0123** [comment]
The bug has not been fixed, so I re-open this issue.
